# Generated by Django 5.2.7 on 2025-11-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField()),
                ('user_id', models.CharField(max_length=100)),
                ('call_back_url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('analysis_result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='output_data',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='job',
            name='input_data',
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='default_job', max_length=255),
        ),
    ]
