# Generated by Django 5.2.7 on 2025-11-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processor', '0002_analyzisdata_rename_output_data_job_data_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalyzisData',
            new_name='AnalysisData',
        ),
    ]
